### ISSUE TITLE
Add message cache option

### ISSUE THREAD

**Issue by mylogon341** [m1k1o/chat#14]
It would be nice to have a config for message count cache on the server for new users to be able to recall. 

Motivation: 
When users' chats disconnect from being backgrounded, when they foreground again it might ask their name again and clears the chat. This is annoying. 

It would also be nice to have an option be able to have new users recall the last n messages for context.

**Comment by m1k1o** [comment]
Fixed by https://github.com/m1k1o/chat/pull/16
