### ISSUE TITLE
Has this project ended?

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [m1k1o/chat#4]
Just wanted to ask if this project is still being maintained. It's a very good application..

**Comment by m1k1o** [comment]
Hello. Yes, this project is still being maintained. Just recently fixed security issue. There have not been many new features in last months, but all PRs are welcomed.

**Comment by m1k1o** [comment]
Just released a new version: https://github.com/m1k1o/chat/releases/tag/v1.1
