### ISSUE TITLE
Proxy from subfolder support

### ISSUE THREAD

**Issue by kimboslice99** [m1k1o/chat#5]
Great work here, just one thought

I've got this setup and working from root domain, but trying to proxy to a subfolder gives 404 errors... would be nice to see this work in both circumstances? 

Thanks,

**Comment by m1k1o** [comment]
Maybe just replacing `/socket.io/socket.io.js` to `socket.io/socket.io.js` in `index.html` could fix that. What is your setup? Can you give some example how to reproduce it?

**Comment by kimboslice99** [comment]
Proxying behind IIS, though I can try with Apache or Nginx just to confirm the issue is present there too

tried removing the slash as suggested, but this brings a new error.... seems now socket.io.js gets loaded but then tries to load sub.domain.tld/socket.io/?EIO=3&transport=polling&t=O7Aq6D0 when it should be looking for sub.domain.tld/chat/socket.io/

**Comment by m1k1o** [comment]
@kimboslice99 latest commit should fix your issue, can you retest?

**Comment by kimboslice99** [comment]
Yup, that seems to have fixed it... working perfect

Thanks!
